src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use App\Repository\QuestionRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Table;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
#[Table(name: 'comments')]
class Comment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false, onDelete: 'CASCADE')]
    private ?Question $question = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column]
    private ?bool $status = true;

    #[ORM\Column]
    private ?\DateTimeImmutable $creation_date = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $update_date = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getQuestion(): ?Question
    {
        return $this->question;
    }

    public function setQuestion(?Question $question): static
    {
        $this->question = $question;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function isStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeImmutable
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeImmutable $creation_date): static
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getUpdateDate(): ?\DateTimeImmutable
    {
        return $this->update_date;
    }

    public function setUpdateDate(\DateTimeImmutable $update_date): static
    {
        $this->update_date = $update_date;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping\Table;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\UserRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['username'], message: 'This username is already taken.')]
#[Table(name: 'users')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

//    #[ORM\Column(length: 255, unique: true, nullable: true)]
    #[ORM\Column(length: 255, unique: true, nullable: true)]
    #[Assert\Length(max: 255)]
    private ?string $username = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column(nullable: true)]
    private ?string $password = null;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE)]
    private ?DateTimeImmutable $inscription_date = null;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE)]
    private ?DateTimeImmutable $last_authentication_date = null;

    /**
     * @var Collection<int, Comment>
     */
    #[ORM\OneToMany(targetEntity: Comment::class, mappedBy: 'user')]
    private Collection $comments;

    /**
     * @var Collection<int, Question>
     */
    #[ORM\OneToMany(targetEntity: Question::class, mappedBy: 'user')]
    private Collection $questions;

    #[ORM\OneToOne(mappedBy: 'user', cascade: ['persist', 'remove'])]
    private ?Score $score = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true, unique: true)]
    private ?string $googleId = null;

    public function __construct()
    {
        $this->inscription_date = new DateTimeImmutable();
        $this->last_authentication_date = new DateTimeImmutable();

        $this->score = new Score();

        $this->score->setWeek(0);
        $this->score->setMonth(0);
        $this->score->setAllTime(0);
        $this->score->setUser($this);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(?string $username): static
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this->username ?? $this->email;
    }

    /**
     * @return list<string>
     * @see UserInterface
     *
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function getInscriptionDate(): ?DateTimeImmutable
    {
        return $this->inscription_date;
    }

    public function setInscriptionDate(DateTimeImmutable $inscription_date): static
    {
        $this->inscription_date = $inscription_date;

        return $this;
    }

    public function getLastAuthenticationDate(): ?DateTimeImmutable
    {
        return $this->last_authentication_date;
    }

    public function setLastAuthenticationDate(DateTimeImmutable $last_authentication_date): static
    {
        $this->last_authentication_date = $last_authentication_date;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Question>
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): static
    {
        if (!$this->questions->contains($question)) {
            $this->questions->add($question);
            $question->setUser($this);
        }

        return $this;
    }

    public function removeQuestion(Question $question): static
    {
        if ($this->questions->removeElement($question)) {
            // set the owning side to null (unless already changed)
            if ($question->getUser() === $this) {
                $question->setUser(null);
            }
        }

        return $this;
    }

    public function getScore(): ?Score
    {
        return $this->score;
    }

    public function setScore(Score $score): static
    {
        // set the owning side of the relation if necessary
        if ($score->getUser() !== $this) {
            $score->setUser($this);
        }

        $this->score = $score;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getGoogleId(): ?string
    {
        return $this->googleId;
    }

    public function setGoogleId(?string $googleId): self
    {
        $this->googleId = $googleId;
        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-GFJ4K1L93N"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-GFJ4K1L93N');
    </script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
    <meta name="theme-color" content="#0f0f0f">
    <title>{% block title %}Quizstack{% endblock %}</title>

    <meta name="description"
          content="{% block meta_description %}Quizstack is a free web development quiz platform to learn HTML, CSS, JavaScript, PHP, SQL and more coding skills on any device. Test our challenges now!{% endblock %}">
    <meta name="robots" content="index, follow">

    <meta property="og:type" content="website">
    <meta property="og:site_name" content="Quizstack">
    <meta property="og:title" content="{% block og_title %}{{ block('title') }}{% endblock %}">
    <meta property="og:description" content="{% block og_description %}{{ block('meta_description') }}{% endblock %}">
    <meta property="og:url" content="{{ absolute_url(app.request.pathInfo) }}">
    <meta property="og:image"
          content="{% block og_image %}{{ absolute_url(asset('images/decoration/quizstack-social.jpg')) }}{% endblock %}">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="{{ block('title') }}">
    <meta name="twitter:description" content="{{ block('meta_description') }}">
    <meta name="twitter:image" content="{{ absolute_url(asset('images/decoration/quizstack-social.jpg')) }}">

    <link rel="canonical" href="{{ absolute_url(app.request.pathInfo) }}">

    <link rel="icon" href="{{ asset('favicon.ico') }}" sizes="any">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preload" as="style" href="https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap"
          media="print" onload="this.media='all'">
    <noscript>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap">
    </noscript>

    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Spline+Sans+Mono:ital,wght@0,300..700;1,300..700&display=swap"
          media="print" onload="this.media='all'">
    <noscript>
        <link rel="stylesheet"
              href="https://fonts.googleapis.com/css2?family=Spline+Sans+Mono:ital,wght@0,300..700;1,300..700&display=swap">
    </noscript>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" media="print"
          onload="this.media='all'">
    <noscript>
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    </noscript>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css">

    {% block stylesheets %}
        {{ encore_entry_link_tags('app') }}
    {% endblock %}

    {% block page_schema %}
        <script type="application/ld+json">
            {
                "@context": "https://schema.org",
                "@graph": [
                    {
                        "@type": "Organization",
                        "@id": "https://quizstack.io/#organization",
                        "name": "Quizstack",
                        "url": "https://quizstack.io/",
                        "logo": "https://quizstack.io/favicon.png",
                        "description": "Free web development quiz platform for HTML, CSS, JavaScript, PHP, SQL, Frontend, Backend, Accessibility, SEO, Security, and Performance",
                        "sameAs": [
                            "https://github.com/FlorianJourde/Quizstack"
                        ]
                    },
                    {
                        "@type": "WebSite",
                        "@id": "https://quizstack.io/#website",
                        "url": "https://quizstack.io/",
                        "name": "Quizstack",
                        "publisher": {
                            "@id": "https://quizstack.io/#organization"
                        }
                    }
                ]
            }
        </script>
    {% endblock %}

    {% block javascripts %}
        {{ encore_entry_script_tags('app') }}
    {% endblock %}
</head>

<body class="bg-very-dark-grey-primary text-white">

{{ include('partials/header.html.twig') }}

{% block body %}{% endblock %}

{{ include('partials/footer.html.twig') }}
{{ include('partials/noise-texture.html.twig') }}
{{ include('partials/overlay.html.twig') }}

</body>
</html>

templates/contact.html.twig
{% extends 'layout.html.twig' %}

{% set title = 'Contact' %}

{% block meta_description %}Have questions about Quizstack ? Contact our team for support with your web development quiz challenges or account issues{% endblock %}

{% block body %}

    {{ include('partials/banner.html.twig') }}

    <div class="wrapper">
        <div class="page-header-container">
            <h1 class="big-title grow">Contact</h1>
        </div>
    </div>

    <div class="wrapper wrapper-small">
        <div class="form-container glass box bg-dark-grey-secondary">

            {{ form_start(form) }}

            <div>
                <h2 class="small-title">
                    <span class="material-icons">alternate_email</span>
                    {{ form.email.vars.label }}
                </h2>
                {{ form_widget(form.email) }}
                {{ form_errors(form.email) }}
            </div>
            <div>
                <h2 class="small-title">
                    <span class="material-icons">person</span>
                    {{ form.username.vars.label }}
                </h2>
                {{ form_widget(form.username) }}
                {{ form_errors(form.username) }}
            </div>
            <div>
                <h2 class="small-title">
                    <span class="material-icons">mail</span>
                    {{ form.message.vars.label }}
                </h2>
                {{ form_widget(form.message) }}
                {{ form_errors(form.message) }}
            </div>

            <div class="buttons-container">
                <a href="{{ path('app_home') }}" class="button button-tertiary">Cancel</a>
                <button type="submit" class="button button-primary">Send</button>
            </div>
            {{ form_end(form) }}

        </div>
    </div>

{% endblock %}

templates/discussions.html.twig
{% extends 'layout.html.twig' %}

{% set title = 'Discussions' %}

{% block meta_description %}See the latest discussions and community engagement on Quizstack - new quizzes, popular challenges, and recent achievements{% endblock %}

{% block body %}

    {{ include('partials/banner.html.twig', {'color': 'purple', 'animate' : 'animate'}) }}

    <div class="wrapper">
        <div class="page-header-container subtitle">
            <h1 class="big-title grow">Discussions</h1>
            <h2 class="fade-in-up md:text-lg opacity-75" style="transition-delay: 0.2s;">
                Share insights, ask questions, and learn faster with developers exploring the same
                web topics
            </h2>
        </div>
    </div>

    <div class="wrapper">
        <div id="discussions-container" data-mode="{{ mode }}"></div>
    </div>

    <div class="wrapper">
        <div class="pt-spacing-very-large-tertiary flex flex-col gap-4">
            <p class="fade-in-up opacity-75" style="transition-delay: 0.2s;">Stay on top of what the
                community is saying. The discussions page collects all recent comments on Quizstack questions, giving
                you a live stream of insights, clarifications, and alternative solutions across our 12 web development
                topics.
            </p>
            <p class="fade-in-up opacity-75" style="transition-delay: 0.2s;">Browse threads connected to
                specific questions in HTML, CSS, JavaScript, React, Node.js, accessibility, performance, testing, and
                more. Filter by topic, difficulty, recency, or popularity to find the discussions that matter most. Skim
                concise explanations, code snippets, and references to documentation shared by contributors.
            </p>
            <p class="fade-in-up opacity-75" style="transition-delay: 0.2s;">Signed-in users can reply, ask for
                clarification, and more... Your participation feeds into badges, streaks, and leaderboard points,
                showcasing your expertise on your profile.
            </p>
            <p class="fade-in-up opacity-75" style="transition-delay: 0.2s;">Quality comes first : community reporting
                and moderation highlight constructive, well-sourced comments and keep conversations respectful. Make
                Discussions part of your routine—check what’s trending, revisit topics you’re practicing, and turn quick
                reading sessions into steady progress.
            </p>
        </div>
    </div>

{% endblock %}

templates/filters.html.twig
{% extends 'layout.html.twig' %}

{% set title = 'Filters' %}

{% block meta_description %}Find the perfect coding quiz by filtering our 1,000+ web development questions by topic or difficulty level{% endblock %}

{% block body %}

    {{ include('partials/banner.html.twig') }}

    <div class="wrapper">
        <div id="filters-section" class="page-header-container subtitle">
            <h1 class="big-title grow">Filters</h1>
            <h2 class="fade-in-up md:text-lg opacity-75" style="transition-delay: 0.2s;">
                Refine your quiz journey : choose filters to match your goals and level
            </h2>
        </div>

        {{ include('partials/filters.html.twig', _context) }}

    </div>

    <div class="wrapper">
        <div class="pt-spacing-very-large-tertiary flex flex-col gap-4">
            <p class="fade-in-up opacity-75" style="transition-delay: 0.2s;">Fine-tune your learning with Filters.
                Select the topics, difficulty levels, and question types that match your goals—whether you’re reviewing
                fundamentals or preparing for a technical interview. You can combine multiple categories like HTML, CSS,
                JavaScript, React, Node.js, accessibility, performance, or testing to build a focused practice set.</p>
            <p class="fade-in-up opacity-75" style="transition-delay: 0.2s;">Use difficulty filters to balance speed and
                challenge, and sort by new, most missed, or highest rated to target high-impact questions. Save your
                favorite filter presets to quickly resume where you left off on mobile or desktop. Logged-in users can
                sync preferences across devices and receive personalized recommendations based on recent activity.</p>
            <p class="fade-in-up opacity-75" style="transition-delay: 0.2s;">Set clear intentions, minimize
                distractions, and practice with purpose. The right filters turn every session into measurable
                progress.</p>
        </div>
    </div>

    {{ include('partials/promotional/promotional-1.html.twig', _context) }}

{% endblock %}

templates/index.html.twig
{% extends 'layout.html.twig' %}

{% set title = 'Learn web development through interactive quiz' %}

{% block body %}

    {{ include('partials/banner.html.twig', {'color': 'green', 'animate' : 'animate'}) }}

    <div class="wrapper wrapper-large pt-spacing-large-secondary pb-spacing-large-secondary">

        <div class="flex flex-col gap-spacing-large-secondary">
            <div class="flex flex-col lg:flex-row gap-spacing-large-secondary items-center lg:items-start">
                <div class="flex flex-col gap-spacing-primary max-w-[600px] mx-auto">
                    <div class="flex flex-col gap-spacing-primary text-center lg:text-left">
                        <div class="flex fade-in-up items-start text-left justify-center lg:justify-start">
                            <p class="flex items-center px-3 py-2 bg-black/50 rounded-radius-secondary text-sm">
                                <span class="material-icons text-[18px] text-green-tertiary mr-2">money_off</span>
                                Completely free to use<span class="hidden sm:block">&nbsp;- no ads or hidden fees</span>
                            </p>
                        </div>
                        <h1 class="text-3xl sm:text-5xl lg:text-[42px] font-bold col-span-full fade-in-up">
                            Learn web development through <span class="text-green-tertiary">interactive quiz</span>
                        </h1>
                        <p class="fade-in-up">Challenge yourself with over 1k+ carefully crafted questions across 12
                            essential web development topics. Perfect your skills in HTML, JavaScript, React, and more -
                            all from your mobile or desktop device, anytime, anywhere.</p>
                    </div>
                    <div class="buttons-container">
                        <a class="button button-tertiary fade-in-up" href="#filters-section">
                            Select filters
                        </a>
                        <a class="button button-primary fade-in-up" href="{{ path('quiz') }}">
                            Play
                        </a>
                    </div>
                </div>
                <div id="demo-container"
                     class="fade-in-up flex justify-center min-h-[480px] w-[600px] max-w-full lg:max-w-[50%]"></div>
            </div>
        </div>
    </div>

    <div class="wrapper wrapper-large pt-spacing-primary pb-spacing-primary">
        <ul class="grid grid-cols-1 max-w-[800px] lg:max-w-full mx-auto lg:grid-cols-3 gap-spacing-primary">
            <li class="card card-pink box glass flex flex-col items-start justify-start">
                <span class="material-icons max-w-[40px] overflow-hidden p-2 text-white-primary mb-4 flex items-center justify-center aspect-square rounded-radius-secondary">question_mark</span>
                <h3 class="text-2xl items-center flex font-bold mb-2">
                    1k+ questions
                </h3>
                <p>Comprehensive quiz library for all skill levels</p>
            </li>
            <li class="card card-green box glass flex flex-col items-start justify-start">
                <span class="material-icons max-w-[40px] overflow-hidden p-2 text-white-primary mb-4 flex items-center justify-center aspect-square rounded-radius-secondary">category</span>
                <h3 class="text-2xl items-center flex font-bold mb-2">
                    12 thematics
                </h3>
                <p>From HTML basics to advanced web security</p>
            </li>
            <li class="card card-blue box glass flex flex-col items-start justify-start">
                <span class="material-icons max-w-[40px] overflow-hidden p-2 text-white-primary mb-4 flex items-center justify-center aspect-square rounded-radius-secondary">group</span>
                <h3 class="text-2xl items-center flex font-bold mb-2">
                    100+ users
                </h3>
                <p>Join developers improving through daily practice</p>
            </li>
        </ul>
    </div>

    <div class="wrapper">
        <div id="filters-section" class="page-header-container">
            <h2 class="big-title grow">Filters</h2>
        </div>
        {{ include('partials/filters.html.twig', _context) }}
    </div>

    {{ include('partials/promotional/promotional-1.html.twig', _context) }}

    <div id="stacks-slider-container" class="pb-spacing-large-primary"></div>

    {{ include('partials/promotional/promotional-2.html.twig', _context) }}
    {{ include('partials/testimonials.html.twig') }}
    {{ include('partials/faq.html.twig') }}

{% endblock %}

templates/layout.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }}{% if title is defined %} | {{ title }}{% endif %}{% endblock %}

templates/question.html.twig
{% extends 'base.html.twig' %}

{% block title %}Question{% endblock %}

{% block body %}
{#    <h1 class="text-3xl">Question</h1>#}

{#    <div id="question-container" data-question-id="{{ question.id }}"></div>#}
{#    <div id="question-container" ></div>#}

{#    <p>{{ question.content }}</p>#}
{#    <br>#}
{#    <h2>Answers</h2>#}
{#    <ul>#}
{#        {% for answer in answers %}#}
{#            <li>{{ answer.content }}</li>#}
{#        {% endfor %}#}
{#    </ul>#}
    {#    <p>{{ question }}</p> #}
    {#    {{ dump(question.content) }} #}


    <div>
        <p class="font-bold text-6xl text-center">Question</p>
    </div>

    <div class="user-info">
        <h1>ID : {{ question.id }}</h1>
        <p>Question : {{ question.content }}</p>
        <p>Image : {{ question.image }}</p>
        <p>Creation date : {{ question.creationDate|date('d/m/Y') }}</p>
        <p>Update date : {{ question.updateDate|date('d/m/Y') }}</p>
        <p>Status : {{ question.status }}</p>
{#        <p>Author : {{ question.user.username }}</p>#}
    </div>

{% endblock %}

{#{% block javascripts %}#}
{#    {{ encore_entry_script_tags('question_app') }}#}
{#        {{ encore_entry_script_tags('app') }}#}
{#{% endblock %}#}


{#{% block javascripts %}#}
{#    {{ encore_entry_script_tags('app') }}#}
{#    {{ encore_entry_script_tags('question_app') }}#}
{#{% endblock %}#}

templates/questions.html.twig
{% extends 'base.html.twig' %}

{% block title %}Questions{% endblock %}

{% block body %}
    <div class="container">
        <h1>Questions listes</h1>

        <div class="questions-list">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Content</th>
                    <th>Image</th>
                    <th>Creation date</th>
                    <th>Update date</th>
                    <th>Status</th>
                    <th>Author</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for question in questions %}
                    <tr>
                        <td>{{ question.id }}</td>
                        <td>{{ question.content }}</td>
                        <td>{{ question.image }}</td>
                        <td>{{ question.creationDate|date('d/m/Y') }}</td>
                        <td>{{ question.updateDate|date('d/m/Y') }}</td>
                        <td>{{ question.status }}</td>
{#                        <td>{{ question.user.username }}</td>#}
                        <td>
                            <a href="{{ path('question', {'id': question.id}) }}" class="btn btn-sm btn-primary">See question</a>
                        </td>

                        {#                        <td>{{ question.userId }}</td> #}
                        {#                        <td> #}
                        {#                            <a href="{{ path('question', {'id': user.id}) }}" class="btn btn-sm btn-primary">Voir la question</a> #}
                        {#                        </td> #}
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="5" class="text-center">Aucun utilisateur trouvé</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/user.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profile{% endblock %}

{% block body %}

{#    <div class="example-wrapper">#}
        <div>
            <p class="font-bold text-6xl text-center">Profile</p>
        </div>

        <div class="user-info">
            <h1>Username :  {{ user.username }}</h1>
            <h1>Email : {{ user.email }}</h1>
{#            <p>Rôle : {{ user.role }}</p>#}
            <p>Dernière connexion : {{ user.lastAuthenticationDate|date('d/m/Y H:i') }}</p>
            <p>Inscription : {{ user.inscriptionDate|date('d/m/Y') }}</p>
        </div>
{#    </div>#}
{% endblock %}

templates/users.html.twig
{% extends 'base.html.twig' %}

{% block title %}Users{% endblock %}

{% block body %}
    <div class="container">
        <h1>Users list</h1>

        <div class="users-list">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Email</th>
                    <th>Username</th>
                    <th>Rôle</th>
                    <th>Date d'inscription</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for user in users %}
                    <tr>
                        <td>{{ user.id }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.username }}</td>
{#                        <td>{{ user.role }}</td>#}
                        <td>{{ user.inscriptionDate|date('d/m/Y') }}</td>
                        <td>
                            <a href="{{ path('user', {'id': user.id}) }}" class="btn btn-sm btn-primary">See profile</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="5" class="text-center">Aucun utilisateur trouvé</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}